capacity:
  admin_email: a.metwalli@groupeonepoint.com
  basename: testcapa
  sku: F2
  tags: null
  workspaces:
    - name: testWorkspace
      users:
        - displayName: John Doe
          emailAddres: j.doe@chanel.com
          groupUserAccessRight: Admin
          identifier: f089354e-8366-4e18-aea3-4cb4a3a50b48
          principalType: App
          profile: displayName
          userType: ''